/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Type definitions for the `codelegate-native` N-API addon.
 *
 * Generated by `pnpm --filter @codelegate/desktop native:build`
 * (`napi build --release --platform --no-js --dts index.d.ts`) and checked in
 * so the Electron main process typechecks without building the crate first.
 *
 * This banner is `native/dts-header.txt`, wired up as `napi.dtsHeaderFile`, so
 * regeneration reproduces it verbatim. Edit that file, never `index.d.ts`.
 *
 * The first version of `index.d.ts` was hand-written against the migration
 * plan's "Native addon surface" contract. If a rebuild changes anything below
 * this banner, the Rust surface drifted from the contract: reconcile rather
 * than silently accepting the new shape. Specifically:
 *  - the `#[napi(object)]` structs must be named `PtySpawnOptions` and
 *    `PtyChunk`;
 *  - byte offsets stay `i64` in Rust on purpose. `u64` maps to BigInt and
 *    would break renderer arithmetic;
 *  - all 13 git functions are async (`AsyncTask` on the libuv pool) and carry
 *    `#[napi(ts_return_type = "...")]` annotations naming the payload types
 *    imported below.
 */
import type {
  GitBranchInfo,
  GitChangeSummaryPayload,
  GitFileDiffPayload,
} from '../electron/shared/types'
/**
 * Cumulative acknowledgement, so a late ack for a session that already exited
 * is simply ignored.
 */
export declare function ackPtyOutput(sessionId: number, throughOffset: number): void

export declare function commitGitChanges(path: string, message: string, amend: boolean): Promise<void>

export declare function discardAllChanges(path: string): Promise<void>

export declare function getGitBranch(path: string): Promise<string>

export declare function getGitChangeSummary(path: string): Promise<GitChangeSummaryPayload>

export declare function getGitFileDiff(path: string, section: string, filePath: string, oldPath?: string | undefined | null): Promise<GitFileDiffPayload>

export declare function getLastCommitMessage(path: string): Promise<string>

export declare function killPty(sessionId: number): void

export declare function listGitBranches(path: string): Promise<Array<GitBranchInfo>>

export interface PtyChunk {
  sessionId: number
  data: Buffer
  /** Cumulative byte offset of the end of this chunk. */
  endOffset: number
}

export interface PtySpawnOptions {
  shell: string
  args: Array<string>
  cwd: string
  env: Record<string, string>
  cols: number
  rows: number
}

export declare function removeSessionWorktree(repoPath: string, worktreePath: string, branch?: string | undefined | null): Promise<void>

export declare function renameGitBranch(path: string, name: string): Promise<string>

export declare function resizePty(sessionId: number, cols: number, rows: number): void

export declare function shutdownAllPty(): void

export declare function spawnPty(options: PtySpawnOptions, onData: (chunk: PtyChunk) => void, onExit: (sessionId: number) => void): number

export declare function stageAllChanges(path: string): Promise<void>

export declare function stageFileChange(path: string, filePath: string): Promise<GitChangeSummaryPayload>

export declare function unstageAllChanges(path: string): Promise<void>

export declare function unstageFileChange(path: string, filePath: string): Promise<GitChangeSummaryPayload>

/**
 * Fire-and-forget: the renderer sends keystrokes over a `MessagePort` and has
 * no channel to receive an error on, so a write to a session that has already
 * exited is dropped rather than thrown.
 */
export declare function writePty(sessionId: number, data: string): void
